In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import KNNImputer

In [5]:
#create dataset for marks of students
dict={'maths':[85,91,np.nan,91],
     'chemistry':[72,75,74,np.nan],
     'physics':[np.nan,86,82,81],
     'biology':[81,81,72,np.nan]}

In [7]:
#creating dataframe from dictionary
before_imputation=pd.DataFrame(dict)
before_imputation

maths  chemistry  physics  biology
0   85.0       72.0      NaN     81.0
1   91.0       75.0     86.0     81.0
2    NaN       74.0     82.0     72.0
3   91.0        NaN     81.0      NaN

In [11]:
#replacing the missing value with KNNImputer
imputer=KNNImputer(n_neighbors=2)
After_imputation=imputer.fit_transform(before_imputation)
After_imputation

array([[85. , 72. , 83.5, 81. ],
       [91. , 75. , 86. , 81. ],
       [91. , 74. , 82. , 72. ],
       [91. , 74.5, 81. , 76.5]])

In [13]:
imputer=KNNImputer(n_neighbors=4)
After_imputation=imputer.fit_transform(before_imputation)
After_imputation

array([[85.        , 72.        , 83.        , 81.        ],
       [91.        , 75.        , 86.        , 81.        ],
       [89.        , 74.        , 82.        , 72.        ],
       [91.        , 73.66666667, 81.        , 78.        ]])

In [14]:
#convert the array to dataframe
df=pd.DataFrame(After_imputation)
df

0          1     2     3
0  85.0  72.000000  83.0  81.0
1  91.0  75.000000  86.0  81.0
2  89.0  74.000000  82.0  72.0
3  91.0  73.666667  81.0  78.0

In [15]:
before_imputation.columns

Index(['maths', 'chemistry', 'physics', 'biology'], dtype='object')

In [16]:
After_imputation=pd.DataFrame(After_imputation,columns=['maths', 'chemistry', 'physics', 'biology'])
After_imputation

maths  chemistry  physics  biology
0   85.0  72.000000     83.0     81.0
1   91.0  75.000000     86.0     81.0
2   89.0  74.000000     82.0     72.0
3   91.0  73.666667     81.0     78.0

In [18]:
x=[[1,3,np.nan,4],[6,np.nan,8,np.nan],[5,4,2,3],[9,np.nan,6,8]]
x

[[1, 3, nan, 4], [6, nan, 8, nan], [5, 4, 2, 3], [9, nan, 6, 8]]

In [20]:
df1=pd.DataFrame(x,columns=['Class A','Class B','Class C','Class D'])
df1

Class A  Class B  Class C  Class D
0        1      3.0      NaN      4.0
1        6      NaN      8.0      NaN
2        5      4.0      2.0      3.0
3        9      NaN      6.0      8.0

In [21]:
df1.isnull()

Class A  Class B  Class C  Class D
0    False    False     True    False
1    False     True    False     True
2    False    False    False    False
3    False     True    False    False

In [22]:
df1.isna().sum()
#no of missing values in each columns

Class A    0
Class B    2
Class C    1
Class D    1
dtype: int64

In [26]:
df1.isna().sum(axis=1)
#no of missing values in each rows

0    1
1    2
2    0
3    1
dtype: int64

In [39]:
A=(df1.isna().sum()).sum()
A

4

In [32]:
df1.count()

Class A    4
Class B    2
Class C    3
Class D    3
dtype: int64

In [40]:
B=df1.count().sum()
B

12

In [42]:
percent=(A)/(B)*100
percent
#excluding the null values



33.33333333333333

In [45]:
# to include missing values add A in denominator
percent1=(A)/(A+B)*100
percent1

25.0

In [47]:
df1.dropna()
#drop the rows having missing values

Class A  Class B  Class C  Class D
2        5      4.0      2.0      3.0

In [49]:
df1.dropna(thresh=3)
#keep the rows having atleast 3 not null values

Class A  Class B  Class C  Class D
0        1      3.0      NaN      4.0
2        5      4.0      2.0      3.0
3        9      NaN      6.0      8.0

In [50]:
#drop column having missing values
df1.dropna(axis=1)

Class A
0        1
1        6
2        5
3        9

In [52]:
df1.dropna(thresh=3,axis=1)
#keep the columns having atleast 3 not null values

Class A  Class C  Class D
0        1      NaN      4.0
1        6      8.0      NaN
2        5      2.0      3.0
3        9      6.0      8.0

In [55]:
df1.mean()
#by default mean values along columns

Class A    5.250000
Class B    3.500000
Class C    5.333333
Class D    5.000000
dtype: float64

In [56]:
# fill the missing value with mean value
df1.fillna(df1.mean())

Class A  Class B   Class C  Class D
0        1      3.0  5.333333      4.0
1        6      3.5  8.000000      5.0
2        5      4.0  2.000000      3.0
3        9      3.5  6.000000      8.0

In [57]:
#replacing the missing value with KNNImputer
imputer=KNNImputer(n_neighbors=2)
df2=imputer.fit_transform(df1)
df2

array([[1. , 3. , 5. , 4. ],
       [6. , 3.5, 8. , 5.5],
       [5. , 4. , 2. , 3. ],
       [9. , 3.5, 6. , 8. ]])

In [60]:
df2=pd.DataFrame(df2,columns=['Class A','Class B','Class C','Class D'])
df2

Class A  Class B  Class C  Class D
0      1.0      3.0      5.0      4.0
1      6.0      3.5      8.0      5.5
2      5.0      4.0      2.0      3.0
3      9.0      3.5      6.0      8.0